Resources:
  IoTCoreRuleSendingToKinesis:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: ${self:custom.serviceName}_${self:custom.stage}_send_to_kinesis_rule_4
      TopicRulePayload:
        Actions:
          - Firehose:
              DeliveryStreamName: !Ref KinesisDeliveryStream
              RoleArn: !GetAtt KinesisRuleRole.Arn
        RuleDisabled: false
        Sql: !Sub
          SELECT topic(3) as clientid FROM '$aws/things/+/shadow/name/+/update/+'

  KinesisRuleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}_${self:custom.stage}_sending_to_kinesis_role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: iot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: Allow
                Action: firehose:PutRecord
                Resource:
                  - !GetAtt KinesisDeliveryStream.Arn
          PolicyName: ${self:service}_${self:custom.stage}_sending_to_kinesis_policy
