Resources:
  KinesisDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${self:custom.stage}-kinesis-delivery-role
      AssumeRolePolicyDocument:
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'

  KinesisDeliveryToS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ${self:service}-${self:custom.stage}-kinesis-delivery-to-s3-policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${self:custom.S3BucketNameForKinesisDestination}'
              - !Sub 'arn:aws:s3:::${self:custom.S3BucketNameForKinesisDestination}*'
      Roles:
        - !Ref KinesisDeliveryRole

  KinesisInvokeLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ${self:service}-${self:custom.stage}-kinesis-invoke-lambda-policy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
            Resource: 
              - !GetAtt TransformLambdaFunction.Arn
      Roles:
        - !Ref KinesisDeliveryRole

  KinesisDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: ${self:service}-${self:custom.stage}-kinesis-delivery-stream
      ExtendedS3DestinationConfiguration:
        S3BackupMode: Enabled
        S3BackupConfiguration: 
          BucketARN: 
            REF: "MyBackupBucket"
           BufferingHints: 
               IntervalInSeconds: "60"
               SizeInMBs: "50"
          RoleARN: !GetAtt KinesisDeliveryRole.Arn
        BucketARN: !Sub 'arn:aws:s3:::${self:custom.S3BucketNameForKinesisDestination}'
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 3
        CompressionFormat: UNCOMPRESSED
        Prefix: firehose/
        RoleARN: !GetAtt KinesisDeliveryRole.Arn
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt TransformLambdaFunction.Arn 
              Type: Lambda

