Resources:
  S3BucketForKinesisDestination: #Create resource for custom s3 bucket that will have the processed data from the lambda function
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.S3BucketNameForKinesisDestination}
      VersioningConfiguration:
        Status: Enabled

  S3BucketForKinesisRaw: #Create resource for s3 bucket that will have the raw and backup s3 bucket from the processed data bucket above 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.S3BucketNameForKinesisRaw}
      VersioningConfiguration:
        Status: Enabled
  
Outputs:
  S3BucketForKinesisDestinationName: #Sets the output for the defined processed bucket
    Value:
      Ref: S3BucketForKinesisDestination

  S3BucketForKinesisRawName: #Sets the outpute for the defined processed bucket
    Value:
      Ref: S3BucketForKinesisRaw